### ISSUE TITLE
config file in nau branch needs updating

### ISSUE THREAD

**Issue by mol3earth** [USGS-Astrogeology/bayleef#25]
the file `bayleef/bayleef/examples/config/config.yaml` has paths that are specific to one developer's file system. 

Should bayleef have a config script that will ask the user for this info, perhaps searching for the files as well? 

Or the README needs to be updated to tell the user to modify the config file.

**Comment by Kelvinrr** [comment]
What might be best is to default those to empty and throw a warning when it's being accessed as reminder to the user that they should set that config var.

**Comment by mol3earth** [comment]
cool. I'll get to this in a bit.

**Comment by mol3earth** [comment]
made PR #26

**Comment by mol3earth** [comment]
PR #26 was merged
